"""Add country_id foreign key to Recipe

Revision ID: 03e9f996f1b9
Revises: 3e87dc58dbe0
Create Date: 2024-07-07 19:21:00.938483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e9f996f1b9'
down_revision = '3e87dc58dbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###
