"""Alter ingredients column from Integer to add ForeignKey

Revision ID: 1d212e88d4ce
Revises: 93c5f6d37f08
Create Date: 2024-07-11 05:52:54.827103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d212e88d4ce'
down_revision = '93c5f6d37f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ingredient_details', ['ingredients'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
