"""Alter how_to_cook column from Integer to add ForeignKey

Revision ID: 606816b931b5
Revises: 84e741979aac
Create Date: 2024-07-11 10:44:01.838548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606816b931b5'
down_revision = '84e741979aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'how_to_cooks', ['how_to_cook'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
