"""add cooking_type_ids column in howtocook table

Revision ID: 6a5122ba3ebd
Revises: 62b57825125e
Create Date: 2024-07-16 09:05:13.178623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5122ba3ebd'
down_revision = '62b57825125e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('how_to_cooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_type_ids', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('how_to_cooks', schema=None) as batch_op:
        batch_op.drop_column('cooking_type_ids')

    # ### end Alembic commands ###
