"""add food table

Revision ID: 7842e21d3151
Revises: 5a137d42f530
Create Date: 2024-07-08 17:00:32.725713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7842e21d3151'
down_revision = '5a137d42f530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_name', sa.String(length=100), nullable=False),
    sa.Column('food_image', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_recipe', schema=None) as batch_op:
        batch_op.drop_constraint('rating_recipe_food_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])
        batch_op.drop_column('food_name')
        batch_op.drop_column('food_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('food_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('food_id')

    with op.batch_alter_table('rating_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_recipe_food_id_fkey', 'recipe', ['food_id'], ['id'])

    op.drop_table('food')
    # ### end Alembic commands ###
