"""add recipes table

Revision ID: 944f3f6dfd55
Revises: 7541dd779ae2
Create Date: 2024-07-11 07:40:12.483797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944f3f6dfd55'
down_revision = '7541dd779ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_info', sa.Text(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('ingredients', sa.Integer(), nullable=True),
    sa.Column('utensils', sa.Integer(), nullable=True),
    sa.Column('how_to_cook', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('cooking_video', sa.String(length=255), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=False),
    sa.Column('dificultly_level', sa.Integer(), nullable=False),
    sa.Column('source_of', sa.String(length=255), nullable=True),
    sa.Column('writen_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['writen_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
