"""Change data type of dose column to String(25)

Revision ID: f51360ea0410
Revises: 1582a474fdf8
Create Date: 2024-07-13 07:52:09.407902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51360ea0410'
down_revision = '1582a474fdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_details', schema=None) as batch_op:
        batch_op.alter_column('dose',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_details', schema=None) as batch_op:
        batch_op.alter_column('dose',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
